Repository DeveloperAcademy-POSTECH/2023-MacC-Team12-Creative8, pull requests merged in 2023-11, with the labels that each got.

#83 SwiftDataManager 수정
  Projects/Core/Sources/Service/SwiftDataManager/SwiftDataManager.swift
Labels: ✨ feature, ver 1.0

#87 SwiftData 구조 변경
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/Model/ArchivedConcertInfo/SaveSetlist.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/a_mcflurry.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, ver 1.0

#91 아카이빙 뷰 수정
  .DS_Store
  Projects/.DS_Store
  Projects/App/Sources/App.swift
  Projects/Core/Sources/Model/LikeArtist/LikeArtistModel.swift
  Projects/Core/Sources/Service/SwiftDataManager/SwiftDataManager.swift
  Projects/Feature/.DS_Store
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveArtistCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveConcertInfoCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/Artist/ConcertListView.swift
  Projects/Feature/Scenes/ArchiveScene/Component/Artist/SeeAllArtist.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArtistSetCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/Block/View/ArchiveYearCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/Block/View/ArchivingConcertBlockView.swift
  Projects/Feature/Scenes/ArchiveScene/Component/Block/View/ArtistSetlistCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/Block/View/BlockAllConcertView.swift
  Projects/Feature/Scenes/ArchiveScene/Component/Block/ViewModel/ArchiveBlcokViewModel.swift
  Projects/Feature/Scenes/ArchiveScene/Component/IsEmptyCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/MenuButton.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/ArchiveScene/ViewModel/ArchivingViewModel.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/MainScene/View/TabBarView.swift
  Projects/Feature/Scenes/SettingScene/View/SettingView.swift
  Setlist.xcworkspace/xcuserdata/a_mcflurry.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, ver 1.0, 🖼️ Design

#84 #78/settingView Design
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/SettingScene/View/ServiceExplainView.swift
  Projects/Feature/Scenes/SettingScene/View/SettingView.swift
  Projects/Feature/Scenes/SettingScene/ViewModel/SettingViewModel.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
Labels: 🖼️ Design

#88 #81/modify artist view
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/Model/ArtistInfoModel.swift
  Projects/Core/Sources/Service/SearchHistoryDataManager/ArtistDataManager.swift
  Projects/Core/Sources/Service/SearchHistoryDataManager/KoreanConverter.swift
  Projects/Core/Sources/Service/SwiftDataManager/SwiftDataManager.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveConcertInfoCell.swift
  Projects/Feature/Scenes/ArtistScene/ArtistView.swift
  Projects/Feature/Scenes/ArtistScene/ArtistViewModel.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, ✨ feature, 🖼️ Design

#89 #52/improve search
  Projects/Core/Sources/Service/SearchHistoryDataManager/ArtistDataManager.swift
  Projects/Core/Sources/Service/SearchHistoryDataManager/KoreanConverter.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistList.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchbarCustom.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
  Projects/Feature/Scenes/SearchScene/ViewModel/SearchViewModel.swift
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, ✨ feature

#90 #80/modify setlist view
  .DS_Store
  Projects/Feature/Scenes/ArtistScene/ArtistView.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/Feature/Scenes/SetlistScene/ViewModel/SetlistViewModel.swift
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, ✨ feature, 🖼️ Design

#92 #76/mainViewModification
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/MainScene/ViewModel/MainViewModel.swift
  Projects/UI/Resources/Images.xcassets/mainViewTicket.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/mainViewTicket.imageset/Ticket.svg
  Projects/UI/UI.xcodeproj/project.pbxproj
Labels: 🐞 fix, ✨ feature, 🖼️ Design

#96 [Fix]#95 - fix some bugs
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArtistScene/ArtistView.swift
  Projects/Feature/Scenes/ArtistScene/ArtistViewModel.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/Feature/Scenes/SetlistScene/ViewModel/SetlistViewModel.swift
  Projects/UI/Resources/Images.xcassets/artistViewTicket.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/artistViewTicket.imageset/artistViewTicket.svg
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, ✨ feature

#98 #97/setlist view design changes
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🖼️ Design

#100 #99/fix artist view
  Projects/Feature/Scenes/ArtistScene/ArtistView.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, 🖼️ Design

#102 #101/modify main view
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Setlist.xcworkspace/xcuserdata/choihyowon.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, ✨ feature

#103 #93/dark mode
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveArtistCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveConcertInfoCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArtistSetCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/IsEmptyCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/MenuButton.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/ArtistScene/ArtistView.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/MainScene/View/TabBarView.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistCell.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistList.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchHistoryCell.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchbarCustom.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/Feature/Scenes/SettingScene/View/ServiceExplainView.swift
  Projects/Feature/Scenes/SettingScene/View/SettingView.swift
  Projects/UI/Resources/Colors.xcassets/blockFontBlack.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/blockOrange.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/blockPink.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/blockWarmgrey.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/fontBlack.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/fontWhite.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/fontWhite2.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/fontWhite3.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/lineGrey2.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/lineWhite1.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/setlistBoxBlack.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/setlistBoxGrey.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/setlistBoxWhite.colorset/Contents.json
  Projects/UI/Resources/Colors.xcassets/toastBurn.colorset/Contents.json
  Projects/UI/Sources/Extensions/ColorExtension.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/choihyowon.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
Labels: ver 1.0, 🖼️ Design

#106 디자인 디테일 & 버그 픽스
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/Service/SwiftDataManager/SwiftDataManager.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveArtistCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveConcertInfoCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/MenuButton.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/ArchiveScene/ViewModel/ArchivingViewModel.swift
  Projects/Feature/Scenes/ArtistScene/ArtistView.swift
  Projects/Feature/Scenes/ArtistScene/ArtistViewModel.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/MainScene/View/TabBarView.swift
  Projects/Feature/Scenes/MainScene/ViewModel/MainViewModel.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistList.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchHistoryCell.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
  Projects/Feature/Scenes/SettingScene/View/SettingView.swift
  Projects/UI/Resources/Images.xcassets/darkTicket.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/darkTicket.imageset/darkTicket.png
  Projects/UI/Resources/Images.xcassets/whiteTicket.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/whiteTicket.imageset/whiteTicket.png
  Projects/UI/Sources/Extensions/DateFormatterExtension.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/a_mcflurry.xcuserdatad/UserInterfaceState.xcuserstate
Labels: ver 1.0, 🖼️ Design

#109 #93/dark mode color 적용
  Projects/App/Resources/Assets.xcassets/logo.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/logo.imageset/logo 1.svg
  Projects/App/Resources/Assets.xcassets/logo.imageset/logo 2.svg
  Projects/App/Resources/Assets.xcassets/logo.imageset/logo 3.svg
  Projects/App/Resources/Assets.xcassets/logo.imageset/logo 4.svg
  Projects/App/Resources/Assets.xcassets/logo.imageset/logo.svg
  Projects/App/Resources/Assets.xcassets/logo.imageset/logoDark 1.svg
  Projects/App/Resources/Assets.xcassets/logo.imageset/logoDark 2.svg
  Projects/App/Resources/Assets.xcassets/logo.imageset/logoDark.svg
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/App/Support/Info.plist
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArtistScene/ArtistView.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/MainScene/View/TabBarView.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
Labels: ver 1.0, 🖼️ Design

#107 #104/main view for release
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/MainScene/Component/ArtistImage.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistSetlistCell.swift
  Projects/Feature/Scenes/MainScene/Component/DarkModeButton.swift
  Projects/Feature/Scenes/MainScene/Component/EmptyMainSetlistView.swift
  Projects/Feature/Scenes/MainScene/Component/EmptyMainView.swift
  Projects/Feature/Scenes/MainScene/Component/ToolbarDarkModeButtons.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/UI/Resources/Images.xcassets/mainViewTicket.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/ticket.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/ticket.imageset/ticket.png
Labels: 🐞 fix, ♻️ refactor

#111 #110/modify artist view
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/Service/SearchHistoryDataManager/ArtistDataManager.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArtistScene/ArtistViewModel.swift
  Projects/Feature/Scenes/ArtistScene/View/AllSetlistsView.swift
  Projects/Feature/Scenes/ArtistScene/View/ArtistInfoView.swift
  Projects/Feature/Scenes/ArtistScene/View/ArtistView.swift
  Projects/Feature/Scenes/ArtistScene/View/BookmarkedSetlistsView.swift
  Projects/Feature/Scenes/ArtistScene/ViewModel/ArtistViewModel.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/Feature/Scenes/SetlistScene/ViewModel/SetlistViewModel.swift
  Projects/UI/Resources/Images.xcassets/artistViewTicket.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/artistViewTicket.imageset/artistViewTicket.png
  Projects/UI/Resources/Images.xcassets/artistViewTicket.imageset/artistViewTicket.svg
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/choihyowon.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, ♻️ refactor, ver 1.0

#113 #112/modify setlist view
  Projects/Core/Sources/Service/SetlistDataService.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/SetlistScene/Component/ExportPlaylistButtonView.swift
  Projects/Feature/Scenes/SetlistScene/Component/SetlistFMLinkButtonView.swift
  Projects/Feature/Scenes/SetlistScene/Component/ToastMessageView.swift
  Projects/Feature/Scenes/SetlistScene/View/BottomModalView.swift
  Projects/Feature/Scenes/SetlistScene/View/BottomView.swift
  Projects/Feature/Scenes/SetlistScene/View/ConcertInfoView.swift
  Projects/Feature/Scenes/SetlistScene/View/EmptySetlistView.swift
  Projects/Feature/Scenes/SetlistScene/View/ListView.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/Feature/Scenes/SetlistScene/ViewModel/SetlistViewModel.swift
  Setlist.xcworkspace/xcuserdata/choihyowon.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, ♻️ refactor, ver 1.0

#117 서치바 디자인 수정
  Projects/Feature/Scenes/SearchScene/Component/SearchbarCustom.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
Labels: 🖼️ Design

#119 구글 애널릭틱스 Adding
  .package.resolved
  Projects/App/.DS_Store
  Projects/App/Project.swift
  Projects/App/Resources/GoogleService-Info.plist
  Projects/App/Sources/App.swift
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/a_mcflurry.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/a_mcflurry.xcuserdatad/xcschemes/xcschememanagement.plist
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✨ feature, ver 1.0

#118 #114/SettingView Padding
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/SettingScene/View/AskView.swift
  Projects/Feature/Scenes/SettingScene/View/ServiceExplainView.swift
  Projects/Feature/Scenes/SettingScene/View/SettingView.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
Labels: ver 1.0, 🖼️ Design

#123 툴바 제거 및 패딩 수정
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/MainScene/Component/EmptyMainView.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/SettingScene/View/SettingView.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/a_mcflurry.xcuserdatad/UserInterfaceState.xcuserstate
Labels: ver 1.0, 🖼️ Design

#124 기다리고 기다리던 newOnboardingView
  .DS_Store
  .package.resolved
  Projects/.DS_Store
  Projects/App/.DS_Store
  Projects/App/Project.swift
  Projects/App/Resources/onboardingArtist.xlsx
  Projects/App/Sources/App.swift
  Projects/Core/.DS_Store
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/Model/OnboardingModel.swift
  Projects/Core/Sources/Service/SearchHistoryDataManager/ArtistDataManager.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Project.swift
  Projects/Feature/Scenes/OnboardingScene/View/OnboardingView.swift
  Projects/Feature/Scenes/OnboardingScene/ViewModel/OnboardingViewModel.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/choihyowon.xcuserdatad/UserInterfaceState.xcuserstate
  Tuist/ProjectDescriptionHelpers/Dependency+Spm.swift
Labels: ✨ feature

#127 [Fix] save woodz
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/Service/APIKeys.swift
  Projects/Core/Sources/Service/SearchHistoryDataManager/ArtistDataManager.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArtistScene/ViewModel/ArtistViewModel.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix

#129 #125/Onboarding Color 적용 끝
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/OnboardingScene/View/OnboardingView.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: ver 1.0, 🖼️ Design

#133 Back Button 과 서치뷰 탭바 사라지는거 구현
  Projects/App/Sources/App.swift
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/Service/SwiftDataManager/SwiftDataManager.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArtistScene/View/ArtistView.swift
  Projects/Feature/Scenes/ArtistScene/View/BookmarkedSetlistsView.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistList.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/a_mcflurry.xcuserdatad/UserInterfaceState.xcuserstate
Labels: ver 1.0, 🖼️ Design

#134 #131/fix artist view
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveConcertInfoCell.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/ArtistScene/View/ArtistInfoView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistSetlistCell.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🖼️ Design

#135 #130/settingview detail 수정
  Projects/Feature/Scenes/SettingScene/View/ServiceExplainView.swift
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
Labels: ver 1.0, 🖼️ Design

#136 #121/modify main view details
  Projects/Feature/Scenes/MainScene/Component/ArtistImage.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistSetlistCell.swift
  Projects/Feature/Scenes/MainScene/Component/DarkModeButton.swift
  Projects/Feature/Scenes/MainScene/Component/EmptyMainSetlistView.swift
  Projects/Feature/Scenes/MainScene/Component/EmptyMainView.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/MainScene/ViewModel/MainViewModel.swift
Labels: 🐞 fix, ♻️ refactor, 🖼️ Design

#137 #128/ search tab artist view - 1.0 찐막 PR
  Projects/App/Resources/onboardingArtist.xlsx
  Projects/App/Resources/~$onboardingArtist.xlsx
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/Model/SearchModel.swift
  Projects/Feature/Scenes/OnboardingScene/ViewModel/OnboardingViewModel.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistCell.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
  Projects/Feature/Scenes/SearchScene/ViewModel/SearchViewModel.swift
  Setlist.xcworkspace/xcuserdata/choihyowon.xcuserdatad/UserInterfaceState.xcuserstate
Labels: ✨ feature, ver 1.0

#141 [Fix]#139 - remove singleton
  Projects/Core/Sources/Service/SearchHistoryDataManager/ArtistDataManager.swift
  Projects/Core/Sources/Service/SearchHistoryDataManager/KoreanConverter.swift
  Projects/Core/Sources/Service/SetlistDataService.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveConcertInfoCell.swift
  Projects/Feature/Scenes/ArtistScene/ViewModel/ArtistViewModel.swift
  Projects/Feature/Scenes/MainScene/ViewModel/MainViewModel.swift
  Projects/Feature/Scenes/OnboardingScene/View/OnboardingView.swift
  Projects/Feature/Scenes/OnboardingScene/ViewModel/OnboardingViewModel.swift
  Projects/Feature/Scenes/SearchScene/ViewModel/SearchViewModel.swift
  Projects/Feature/Scenes/SetlistScene/ViewModel/SetlistViewModel.swift
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix

#146 #144/resolveQAIssue
  Projects/Core/Sources/Model/SetlistListModel.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveArtistCell.swift
  Projects/Feature/Scenes/ArtistScene/View/ArtistInfoView.swift
  Projects/Feature/Scenes/ArtistScene/View/ArtistView.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/OnboardingScene/View/OnboardingView.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
  Projects/Feature/Scenes/SetlistScene/View/ListView.swift
Labels: 🐞 fix, ✨ feature

#150 #143/메인 뷰 수정
  Projects/App/Sources/App.swift
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/.DS_Store
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/MainScene/Component/ArtistImage.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistNameView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistSetlistCell.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistsContentView.swift
  Projects/Feature/Scenes/MainScene/Component/DarkModeButton.swift
  Projects/Feature/Scenes/MainScene/Component/EmptyMainSetlistView.swift
  Projects/Feature/Scenes/MainScene/Component/EmptyMainView.swift
  Projects/Feature/Scenes/MainScene/Component/ToolbarDarkModeButtons.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
Labels: ♻️ refactor, 🖼️ Design

#151 #142/SettingView 수정
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/MainScene/View/TabBarView.swift
  Projects/Feature/Scenes/SettingScene/View/LanguageView.swift
  Projects/Feature/Scenes/SettingScene/View/ServiceExplainView.swift
  Projects/Feature/Scenes/SettingScene/View/SettingView.swift
  Projects/Feature/Scenes/SettingScene/ViewModel/SettingViewModel.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🖼️ Design, ver 1.1

#153 [Fix]#152 - modify array for exporting playlist
  .DS_Store
  Projects/Core/Sources/CaptureSetlist/CaptureSetlistView.swift
  Projects/Core/Sources/Service/AppleMusicService.swift
  Projects/Feature/Scenes/SetlistScene/Component/ExportPlaylistButtonView.swift
  Projects/Feature/Scenes/SetlistScene/View/BottomModalView.swift
  Projects/Feature/Scenes/SetlistScene/View/ListView.swift
  Projects/Feature/Scenes/SetlistScene/ViewModel/SetlistViewModel.swift
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix

#154 #145/playlist modal view redesign
  .DS_Store
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/CaptureSetlist/CaptureSetlistView.swift
  Projects/Core/Sources/ShareSetlist/ShareSetlistView.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/SetlistScene/Component/CustomTitleAlert.swift
  Projects/Feature/Scenes/SetlistScene/Component/ExportPlaylistButtonView.swift
  Projects/Feature/Scenes/SetlistScene/View/BottomModalView.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/Feature/Scenes/SetlistScene/ViewModel/ExportPlaylistViewModel.swift
  Projects/Feature/Scenes/SetlistScene/ViewModel/SetlistViewModel.swift
  Projects/UI/Resources/Images.xcassets/AppImages/Contents.json
  Projects/UI/Resources/Images.xcassets/AppImages/appleMusic.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/AppImages/appleMusic.imageset/appleMusic.png
  Projects/UI/Resources/Images.xcassets/AppImages/spotify.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/AppImages/spotify.imageset/spotify.png
  Projects/UI/Resources/Images.xcassets/AppImages/youtubeMusic.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/AppImages/youtubeMusic.imageset/youtubeMusic.png
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
Labels: ✨ feature, 🖼️ Design

#156 #148/View 수정
  .DS_Store
  Projects/App/Sources/App.swift
  Projects/Core/Sources/CaptureSetlist/CaptureSetlistView.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveConcertInfoCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArtistSetCell.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/ArtistScene/View/AllSetlistsView.swift
  Projects/Feature/Scenes/ArtistScene/View/ArtistInfoView.swift
  Projects/Feature/Scenes/ArtistScene/View/BookmarkedSetlistsView.swift
  Projects/Feature/Scenes/MainScene/View/TabBarView.swift
  Projects/Feature/Scenes/OnboardingScene/View/OnboardingView.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
Labels: 🖼️ Design, ver 1.1

#159 #158/add server onboarding
  .DS_Store
  Projects/App/Resources/onboardingArtist.xlsx
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/CaptureSetlist/CaptureSetlistView.swift
  Projects/Core/Sources/Model/OnboardingModel.swift
  Projects/Core/Sources/Service/ArtistFetchService.swift
  Projects/Core/Sources/Service/SwiftDataManager/SwiftDataManager.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveArtistCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveConcertInfoCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArtistSetCell.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/ArtistScene/View/AllSetlistsView.swift
  Projects/Feature/Scenes/ArtistScene/View/ArtistInfoView.swift
  Projects/Feature/Scenes/ArtistScene/View/BookmarkedSetlistsView.swift
  Projects/Feature/Scenes/MainScene/View/TabBarView.swift
  Projects/Feature/Scenes/OnboardingScene/View/OnboardingView.swift
  Projects/Feature/Scenes/OnboardingScene/ViewModel/OnboardingViewModel.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistCell.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
  Projects/Feature/Scenes/SearchScene/ViewModel/SearchViewModel.swift
  Projects/UI/Resources/Colors.xcassets/lineGrey1.colorset/Contents.json
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/a_mcflurry.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/a_mcflurry.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
Labels: 🐞 fix, ✨ feature, ver 1.1

#161 #157/modify detail
  Projects/Feature/Scenes/ArtistScene/View/BookmarkedSetlistsView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistNameView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistsContentView.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/SetlistScene/Component/CustomTitleAlert.swift
  Projects/Feature/Scenes/SetlistScene/Component/SetlistFMLinkButtonView.swift
  Projects/Feature/Scenes/SetlistScene/View/BottomModalView.swift
  Projects/Feature/Scenes/SetlistScene/View/BottomView.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/Feature/Scenes/SetlistScene/ViewModel/ExportPlaylistViewModel.swift
Labels: 🐞 fix, ♻️ refactor, 🖼️ Design

#164 검색기록 중복 제거
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/Service/SwiftDataManager/SwiftDataManager.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistList.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/a_mcflurry.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, ver 1.1

#165 #162/localization
  .DS_Store
  Projects/.DS_Store
  Projects/App/.DS_Store
  Projects/App/Localizable.xcstrings
  Projects/Core/.DS_Store
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/Model/OnboardingModel.swift
  Projects/Core/Sources/Service/SearchHistoryDataManager/KoreanConverter.swift
  Projects/Feature/.DS_Store
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Localizable.xcstrings
  Projects/Feature/Scenes/.DS_Store
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveConcertInfoCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArtistSetCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/IsEmptyCell.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/ArtistScene/View/AllSetlistsView.swift
  Projects/Feature/Scenes/ArtistScene/ViewModel/ArtistViewModel.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistNameView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistsContentView.swift
  Projects/Feature/Scenes/MainScene/Component/EmptyMainSetlistView.swift
  Projects/Feature/Scenes/MainScene/ViewModel/MainViewModel.swift
  Projects/Feature/Scenes/OnboardingScene/View/OnboardingView.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchbarCustom.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
  Projects/Feature/Scenes/SetlistScene/Component/ToastMessageView.swift
  Projects/Feature/Scenes/SetlistScene/View/ConcertInfoView.swift
  Projects/Feature/Scenes/SetlistScene/View/EmptySetlistView.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/Feature/Scenes/SetlistScene/ViewModel/SetlistViewModel.swift
  Projects/Feature/Scenes/SettingScene/View/ServiceExplainView.swift
  Projects/Feature/Scenes/SettingScene/View/SettingView.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
Labels: 📝 docs, ✨ feature

#170 #155/tab bar item
  .DS_Store
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Core/Sources/Model/ArtistInfoModel/SaveArtistInfo.swift
  Projects/Core/Sources/Service/APIKeys.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveConcertInfoCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/MenuButton.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/ArchiveScene/ViewModel/ArchivingViewModel.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistNameView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistsContentView.swift
  Projects/Feature/Scenes/MainScene/Component/EmptyMainSetlistView.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/MainScene/View/TabBarView.swift
  Projects/Feature/Scenes/MainScene/ViewModel/MainViewModel.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistCell.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistList.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
Labels: ✨ feature, ver 1.1

#173 #167/Search, Archive 수정, delete Setting file
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/ArchiveScene/Component/ArtistSetCell.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistCell.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistList.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchHistoryCell.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchbarCustom.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
  Projects/Feature/Scenes/SettingScene/View/LanguageView.swift
  Projects/Feature/Scenes/SettingScene/View/ServiceExplainView.swift
  Projects/Feature/Scenes/SettingScene/View/SettingView.swift
  Projects/Feature/Scenes/SettingScene/ViewModel/SettingViewModel.swift
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, 🖼️ Design, ver 1.1

#177 #174/탭바 투명, 보관함 다크모드
  .DS_Store
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/MainScene/View/TabBarView.swift
  Setlist.xcworkspace/xcuserdata/kohyeji.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
Labels: 🐞 fix, ver 1.1
