Repository DeveloperAcademy-POSTECH/2023-MacC-Team12-Creative8, pull requests merged in 2024-08, with the labels that each got.

#230 #212/main view2.0
  .package.resolved
  Projects/App/Seta.entitlements
  Projects/App/Support/Info.plist
  Projects/Core/Sources/Model/SearchModel.swift
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Project.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveArtistCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveConcertInfoCell.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingArtistView.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/ArchiveScene/ViewModel/ArchivingViewModel.swift
  Projects/Feature/Scenes/ArtistScene/View/ArtistView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistImage.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistMainSetlistView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistNameView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistsContentView.swift
  Projects/Feature/Scenes/MainScene/Component/EmptyMainSetlistView.swift
  Projects/Feature/Scenes/MainScene/Component/MainToolTipView.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/MainScene/ViewModel/MainViewModel.swift
  Projects/Feature/Scenes/SetlistScene/Component/CustomTitleAlert.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistImageShareView.swift
  Projects/Feature/Scenes/SetlistScene/ViewModel/SetlistViewModel.swift
  Projects/Feature/Scenes/SummarizedSetlistInfoView.swift
  Setlist.xcworkspace/xcuserdata/choihyowon.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
  Tuist/ProjectDescriptionHelpers/Dependency+Spm.swift
Labels: ✨ feature, ver 2.0

#233 탭바 아이콘 바꾸기
  Projects/Core/Core.xcodeproj/project.pbxproj
  Projects/Feature/Feature.xcodeproj/project.pbxproj
  Projects/Feature/Scenes/MainScene/View/TabBarView.swift
  Projects/UI/Resources/Images.xcassets/archiveIcon.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/archiveIcon.imageset/archiveIcon.svg
  Projects/UI/Resources/Images.xcassets/searchIcon.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/searchIcon.imageset/searchIcon.svg
  Projects/UI/Resources/Images.xcassets/setlistIcon.imageset/Contents.json
  Projects/UI/Resources/Images.xcassets/setlistIcon.imageset/setlistIcon.svg
  Projects/UI/UI.xcodeproj/project.pbxproj
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/UserInterfaceState.xcuserstate
  Setlist.xcworkspace/xcuserdata/yeseul.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: 🖼️ Design

#238 #235/ MainView QA 및 애플뮤직 속도 개선
  Projects/Core/Sources/Service/AppleMusicService.swift
  Projects/Feature/Project.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingArtistView.swift
  Projects/Feature/Scenes/ArtistScene/View/ArtistInfoView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistImage.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistMainSetlistView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistNameView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistsContentView.swift
  Projects/Feature/Scenes/MainScene/Component/EmptyMainView.swift
  Projects/Feature/Scenes/MainScene/Component/MainToolTipView.swift
  Projects/Feature/Scenes/MainScene/View/MainView.swift
  Projects/Feature/Scenes/MainScene/ViewModel/MainViewModel.swift
  Projects/Feature/Scenes/SetlistScene/Component/CustomTitleAlert.swift
  Projects/Feature/Scenes/SetlistScene/Component/ExportPlaylistButtonView.swift
  Projects/Feature/Scenes/SummarizedSetlistInfoView.swift
  Tuist/ProjectDescriptionHelpers/Dependency+Spm.swift
Labels: ver 2.0

#242 [FIX]#241 - 서치 티켓이미지, 아티스트 출현 알고리즘, UI수정
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveArtistCell.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistImage.swift
  Projects/Feature/Scenes/SearchScene/Component/SearchArtistCell.swift
  Projects/Feature/Scenes/SearchScene/View/SearchView.swift
  Projects/Feature/Scenes/SearchScene/ViewModel/SearchViewModel.swift
Labels: ver 2.0

#243 [feat]#228 - 현지화, 현지화 위한 코드 수정, 아카이브 뷰 수정
  Projects/App/Localizable.xcstrings
  Projects/Feature/Localizable.xcstrings
  Projects/Feature/Scenes/ArchiveScene/Component/ArchiveConcertInfoCell.swift
  Projects/Feature/Scenes/ArchiveScene/Component/IsEmptyCell.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingArtistView.swift
  Projects/Feature/Scenes/ArchiveScene/View/ArchivingView.swift
  Projects/Feature/Scenes/ArchiveScene/ViewModel/ArchivingViewModel.swift
  Projects/Feature/Scenes/ArtistScene/View/AllSetlistsView.swift
  Projects/Feature/Scenes/MainScene/Component/ArtistMainSetlistView.swift
  Projects/Feature/Scenes/MainScene/Component/MainToolTipView.swift
  Projects/Feature/Scenes/MainScene/ViewModel/MainViewModel.swift
  Projects/Feature/Scenes/OnboardingScene/View/OnboardingView.swift
  Projects/Feature/Scenes/OnboardingScene/ViewModel/OnboardingViewModel.swift
  Projects/Feature/Scenes/SetlistScene/Component/ExportPlaylistButtonView.swift
  Projects/Feature/Scenes/SetlistScene/Component/ShareOptionButtonView.swift
  Projects/Feature/Scenes/SetlistScene/View/BottomModalView.swift
  Projects/Feature/Scenes/SetlistScene/View/EmptySetlistView.swift
  Projects/Feature/Scenes/SetlistScene/View/SetlistView.swift
  Projects/Feature/Scenes/SetlistScene/ViewModel/SetlistViewModel.swift
  Projects/Feature/Scenes/SummarizedSetlistInfoView.swift
Labels: 📝 docs, ♻️ refactor, ver 2.0
